# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Dev-Regression

on:
  [workflow_dispatch]
    
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./QaAutomation/package-lock.json
      
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d_%H%M%S')"
        
    - name: Install dependencies
      run: |
        cd $GITHUB_WORKSPACE
        cd QaAutomation
        npm install
        npm install newman
        npm install balanced-match
        npm install newman-reporter-allure
        npm install newman-reporter-html
        npm install newman-reporter-htmlextra
        npm install newman-reporter-json-summary
        npm install request
        npm install request-promise
        npm audit fix
        
    - name: Running NydigProvider-MarketData
      run: |
        cd QaAutomation
        mkdir newman        
        node "./newman-run.js" "./NydigProvider-MarketData.postman_collection.json" "./NCR.postman_globals.json" "./NydigProvider_Dev.postman_environment.json"
        node "./newman-run.js" "./NydigProvider-Users.postman_collection.json" "./NCR.postman_globals.json" "./NydigProvider_Dev.postman_environment.json"
        node "./newman-run.js" "./NydigProvider-Accounts.postman_collection.json" "./NCR.postman_globals.json" "./NydigProvider_Dev.postman_environment.json"
        node "./newman-run.js" "./NydigProvider-Orders.postman_collection.json" "./NCR.postman_globals.json" "./NydigProvider_Dev.postman_environment.json"
     
    - name: Display structure of downloaded files
      run: |
        cd QaAutomation
        ls -a
        
    - uses: actions/upload-artifact@v2      
      name: QA Regression Run
      with:
        name: QARegression-Run-artifact-${{ steps.date.outputs.date }}
        path: |
          ${{ github.workspace }}/QaAutomation/newman/
          ${{ github.workspace }}/QaAutomation/allure-report/
          ${{ github.workspace }}/QaAutomation/allure-results/
          ${{ github.workspace }}/QaAutomation/NydigProvider-*/
          ${{ github.workspace }}/QaAutomation/openAllureReport.ps1
