# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Nydig PM API Automation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./QaAutomation/package-lock.json
    #- name: Change Directory to QAAutomation
      
    - name: Install dependencies
      run: |
        cd QaAutomation
        npm install
        npm install newman
        npm install balanced-match
        npm install newman-reporter-allure
        npm install newman-reporter-html
        npm install newman-reporter-htmlextra
        npm install newman-reporter-json-summary
        npm install request
        npm install request-promise
        npm audit fix
    - name: Running NydigProvider-MarketData
      run: |
        cd QaAutomation
        mkdir newman
        node "./newman-run.js" "./NydigProvider-MarketData.postman_collection.json" "./NCR.postman_globals.json" "./NydigProvider_Dev.postman_environment.json"
        node "./newman-run.js" "./NydigProvider-Users.postman_collection.json" "./NCR.postman_globals.json" "./NydigProvider_Dev.postman_environment.json"
        node "./newman-run.js" "./NydigProvider-Accounts.postman_collection.json" "./NCR.postman_globals.json" "./NydigProvider_Dev.postman_environment.json"
        node "./newman-run.js" "./NydigProvider-Orders.postman_collection.json" "./NCR.postman_globals.json" "./NydigProvider_Dev.postman_environment.json"
        cd newman
        dir
        echo =======================
        pwd
        env
    - name: Read file contents
      id: read_file
      uses: andstor/file-reader-action@v1
      with:
        path: "/home/runner/work/sm251296/sm251296/QaAutomation/newman/Result.json"
        
    - name: File contents
      run:  echo "${{ steps.read_file.outputs.contents }}"
