# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Regression

on:
  workflow_dispatch:
    inputs:
      testenvironment:
        description: 'Environment (DEV/QA/PTE)'     
        required: true
        default: 'QA'
      tags:
        description: 'Test scenario tags'   
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./QaAutomation/package-lock.json
      
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d_%H%M%S')"
        
    - name: Install dependencies
      run: |
        cd $GITHUB_WORKSPACE
        cd QaAutomation
        npm install
        npm install newman
        npm install balanced-match
        npm install newman-reporter-allure
        npm install newman-reporter-html
        npm install newman-reporter-htmlextra
        npm install newman-reporter-json-summary
        npm install request
        npm install request-promise
        npm audit fix
        
    - name: Running NydigProvider-APIs
      run: |
        cd QaAutomation
        mkdir newman        
        node "./newman-run.js" "./NydigProvider-MarketData.postman_collection.json" "./NCR.postman_globals.json" "./NydigProvider_Dev.postman_environment.json"
        # node "./newman-run.js" "./NydigProvider-Users.postman_collection.json" "./NCR.postman_globals.json" "./NydigProvider_Dev.postman_environment.json"
        # node "./newman-run.js" "./NydigProvider-Accounts.postman_collection.json" "./NCR.postman_globals.json" "./NydigProvider_Dev.postman_environment.json"
        # node "./newman-run.js" "./NydigProvider-Orders.postman_collection.json" "./NCR.postman_globals.json" "./NydigProvider_Dev.postman_environment.json"
     
    - name: Display structure of downloaded files
      run: |
        cd QaAutomation
        ls -a
        
    - uses: actions/upload-artifact@v2      
      name: Dev - Regression Run
      with:
        name: Dev-Regression-Run-artifact-${{ steps.date.outputs.date }}
        path: |
          ${{ github.workspace }}/QaAutomation/newman/
          ${{ github.workspace }}/QaAutomation/allure-report/
          ${{ github.workspace }}/QaAutomation/allure-results/
          ${{ github.workspace }}/QaAutomation/NydigProvider-*/*.html
          ${{ github.workspace }}/QaAutomation/openAllureReport.ps1
   
    - name: Read package.json
      id: package
      uses: juliangruber/read-file-action@v1
      with:
        path: ${{ github.workspace }}/QaAutomation/newman/Result.json
      
    - name: Echo Results.json
      run: |
        content="${{ steps.package.outputs.content }}"
        echo "::set-output name=packageJson::$content"
        echo "${{fromJson(steps.set_var.outputs.packageJson).Run.Stats.Assertions.failed}}"
        echo "${{ steps.package.outputs.content }}"
        echo "--------------------------------------------------------------"
        echo "${{ steps.package.outputs.content.Run.Stats.Assertions.failed}}"
        echo "${{fromJson(steps.set_var.outputs.packageJson).version}}"
        echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
    
    - name: TestResults Check
      if: ${{steps.package.outputs.content.Run.Stats.Assertions.failed}} > 0
      uses: actions/github-script@v3
      with:
        script: |
          core.setFailed('Some tests failed')
